name: Update users, characters, honor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: curl, mbstring

      - name: Build users JSON
        env:
          UCOZ_CONSUMER_KEY: ${{ secrets.UCOZ_CONSUMER_KEY }}
          UCOZ_CONSUMER_SECRET: ${{ secrets.UCOZ_CONSUMER_SECRET }}
          UCOZ_TOKEN: ${{ secrets.UCOZ_TOKEN }}
          UCOZ_TOKEN_SECRET: ${{ secrets.UCOZ_TOKEN_SECRET }}
        run: php build_users_with_www.php

      - name: Build characters JSON
        run: php build_characters_from_users.php

      - name: Build rating
        env:
          BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
          BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
        run: php build_rating.php


      - name: Commit result
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Update data" || exit 0
          git push
